### Multi Linear Regression
![Image of Yaktocat](https://miro.medium.com/max/1000/1*k2bLmeYIG7z7dCyxADedhQ.png)


### Variable Selection
* All variable
* Backward Elimination
    significance Level
    * every columns if p>
    p > SL
* Forward Selection
    * firstly selcet one variable
    * then add variable test p value en kçkük p hold
* Bidirectitonal Elimination
* Score Comparsion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv('datas.csv',sep=',')
data.head()

country  height  weight  age gender
0      tr     130      30   10      e
1      tr     125      36   11      e
2      tr     135      34   10      k
3      tr     133      30    9      k
4      tr     129      38   12      e

In [24]:
temp_data = data.values

In [3]:
country = data.iloc[:,0:1].values
country

array([['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr']], dtype=object)

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
country[:,0] = le.fit_transform(data.iloc[:,0])
country

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=object)

In [5]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
country = ohe.fit_transform(country).toarray()
country

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [6]:
gender = data.iloc[:,-1:].values
gender[:,-1] = le.fit_transform(data.iloc[:,-1])
gender = ohe.fit_transform(gender).toarray()
gender

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [7]:
s1 = pd.DataFrame(data = country, index = range(22), columns=['fr','tr','us'] )
s2 = pd.DataFrame(data = gender[:,:1] , index=range(22), columns=['gender'])
s3 = data.iloc[:,1:4]


In [8]:
d1=pd.concat([s1,s3],axis=1)
data2=pd.concat([d1,s2],axis=1)
data2

fr   tr   us  height  weight  age  gender
0   0.0  1.0  0.0     130      30   10     1.0
1   0.0  1.0  0.0     125      36   11     1.0
2   0.0  1.0  0.0     135      34   10     0.0
3   0.0  1.0  0.0     133      30    9     0.0
4   0.0  1.0  0.0     129      38   12     1.0
5   0.0  1.0  0.0     180      90   30     1.0
6   0.0  1.0  0.0     190      80   25     1.0
7   0.0  1.0  0.0     175      90   35     1.0
8   0.0  1.0  0.0     177      57   22     0.0
9   0.0  0.0  1.0     185     105   33     1.0
10  0.0  0.0  1.0     165      55   27     0.0
11  0.0  0.0  1.0     155      50   44     0.0
12  0.0  0.0  1.0     160      58   39     0.0
13  0.0  0.0  1.0     162      59   41     0.0
14  0.0  0.0  1.0     167      62   55     0.0
15  1.0  0.0  0.0     174      70   47     1.0
16  1.0  0.0  0.0     193      90   23     1.0
17  1.0  0.0  0.0     187      80   27     1.0
18  1.0  0.0  0.0     183      50   28     1.0
19  1.0  0.0  0.0     159      40   29     0.0
20  1.0  0.0  0.0     164      66   32     0.0
21  1.0  0.0  0.0     166      56   42     0.0

In [9]:
x_data = data2.iloc[:,:-1]
x_data

fr   tr   us  height  weight  age
0   0.0  1.0  0.0     130      30   10
1   0.0  1.0  0.0     125      36   11
2   0.0  1.0  0.0     135      34   10
3   0.0  1.0  0.0     133      30    9
4   0.0  1.0  0.0     129      38   12
5   0.0  1.0  0.0     180      90   30
6   0.0  1.0  0.0     190      80   25
7   0.0  1.0  0.0     175      90   35
8   0.0  1.0  0.0     177      57   22
9   0.0  0.0  1.0     185     105   33
10  0.0  0.0  1.0     165      55   27
11  0.0  0.0  1.0     155      50   44
12  0.0  0.0  1.0     160      58   39
13  0.0  0.0  1.0     162      59   41
14  0.0  0.0  1.0     167      62   55
15  1.0  0.0  0.0     174      70   47
16  1.0  0.0  0.0     193      90   23
17  1.0  0.0  0.0     187      80   27
18  1.0  0.0  0.0     183      50   28
19  1.0  0.0  0.0     159      40   29
20  1.0  0.0  0.0     164      66   32
21  1.0  0.0  0.0     166      56   42

In [10]:
y_data = data2.iloc[:,-1:]
y_data

gender
0      1.0
1      1.0
2      0.0
3      0.0
4      1.0
5      1.0
6      1.0
7      1.0
8      0.0
9      1.0
10     0.0
11     0.0
12     0.0
13     0.0
14     0.0
15     1.0
16     1.0
17     1.0
18     1.0
19     0.0
20     0.0
21     0.0

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(x_data,y_data,test_size=0.33, random_state=0)


In [12]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()

In [13]:
lin_reg.fit(x_train,y_train)

LinearRegression()

In [14]:
y_pred = lin_reg.predict(x_test) #tahmin
print(y_pred)
print(y_test)

[[1.13175648]
 [0.07151376]
 [0.15493907]
 [0.17555518]
 [0.63294185]
 [0.89159699]
 [0.08116664]
 [0.67386003]]
    gender
20     0.0
10     0.0
14     0.0
13     0.0
1      1.0
21     0.0
11     0.0
19     0.0


In [30]:
height = data2.iloc[:,3:4].values
height

array([[130],
       [125],
       [135],
       [133],
       [129],
       [180],
       [190],
       [175],
       [177],
       [185],
       [165],
       [155],
       [160],
       [162],
       [167],
       [174],
       [193],
       [187],
       [183],
       [159],
       [164],
       [166]])

In [31]:
t1 = data2.iloc[:,:3]
t2 = data2.iloc[:,4:]
data3 = pd.concat([t1,t2],axis=1)
data3

fr   tr   us  weight  age  gender
0   0.0  1.0  0.0      30   10     1.0
1   0.0  1.0  0.0      36   11     1.0
2   0.0  1.0  0.0      34   10     0.0
3   0.0  1.0  0.0      30    9     0.0
4   0.0  1.0  0.0      38   12     1.0
5   0.0  1.0  0.0      90   30     1.0
6   0.0  1.0  0.0      80   25     1.0
7   0.0  1.0  0.0      90   35     1.0
8   0.0  1.0  0.0      57   22     0.0
9   0.0  0.0  1.0     105   33     1.0
10  0.0  0.0  1.0      55   27     0.0
11  0.0  0.0  1.0      50   44     0.0
12  0.0  0.0  1.0      58   39     0.0
13  0.0  0.0  1.0      59   41     0.0
14  0.0  0.0  1.0      62   55     0.0
15  1.0  0.0  0.0      70   47     1.0
16  1.0  0.0  0.0      90   23     1.0
17  1.0  0.0  0.0      80   27     1.0
18  1.0  0.0  0.0      50   28     1.0
19  1.0  0.0  0.0      40   29     0.0
20  1.0  0.0  0.0      66   32     0.0
21  1.0  0.0  0.0      56   42     0.0

In [32]:
x_train, x_test,y_train,y_test = train_test_split(data3,height,test_size=0.33, random_state=0)


In [33]:
lin_reg.fit(x_train,y_train)

LinearRegression()

In [34]:
y_pred = lin_reg.predict(x_test) #tahmin
print(y_pred)
print(y_test)

[[189.51722943]
 [154.3572057 ]
 [164.65192905]
 [159.91902513]
 [134.18893282]
 [182.83247237]
 [152.94010491]
 [167.48410654]]
[[164]
 [165]
 [167]
 [162]
 [125]
 [166]
 [155]
 [159]]


In [35]:
backward elimaniton

SyntaxError: invalid syntax (<ipython-input-35-cb130394f91c>, line 1)

In [20]:
import statsmodels.api as sm

In [29]:
X = np.append(arr = np.ones((22,1)).astype(int),values=data3,axis=1) #b0
X

array([[  1.,   0.,   1.,   0.,  30.,  10.,   1.],
       [  1.,   0.,   1.,   0.,  36.,  11.,   1.],
       [  1.,   0.,   1.,   0.,  34.,  10.,   0.],
       [  1.,   0.,   1.,   0.,  30.,   9.,   0.],
       [  1.,   0.,   1.,   0.,  38.,  12.,   1.],
       [  1.,   0.,   1.,   0.,  90.,  30.,   1.],
       [  1.,   0.,   1.,   0.,  80.,  25.,   1.],
       [  1.,   0.,   1.,   0.,  90.,  35.,   1.],
       [  1.,   0.,   1.,   0.,  57.,  22.,   0.],
       [  1.,   0.,   0.,   1., 105.,  33.,   1.],
       [  1.,   0.,   0.,   1.,  55.,  27.,   0.],
       [  1.,   0.,   0.,   1.,  50.,  44.,   0.],
       [  1.,   0.,   0.,   1.,  58.,  39.,   0.],
       [  1.,   0.,   0.,   1.,  59.,  41.,   0.],
       [  1.,   0.,   0.,   1.,  62.,  55.,   0.],
       [  1.,   1.,   0.,   0.,  70.,  47.,   1.],
       [  1.,   1.,   0.,   0.,  90.,  23.,   1.],
       [  1.,   1.,   0.,   0.,  80.,  27.,   1.],
       [  1.,   1.,   0.,   0.,  50.,  28.,   1.],
       [  1.,   1.,   0.,   0.,

In [40]:
X_l = data3.iloc[:,[0,1,2,3,4,5]].values
X_l = np.array(X_l,dtype=float)
model = sm.OLS(height,X_l).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.806
Model:                            OLS   Adj. R-squared:                  0.746
Method:                 Least Squares   F-statistic:                     13.32
Date:                Mon, 05 Dec 2022   Prob (F-statistic):           3.16e-05
Time:                        02:43:22   Log-Likelihood:                -79.709
No. Observations:                  22   AIC:                             171.4
Df Residuals:                      16   BIC:                             178.0
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           122.7339     10.170     12.068      0.0

In [ ]:
> Emove big p value 

In [41]:
X_l = data3.iloc[:,[0,1,2,3,4]].values
X_l = np.array(X_l,dtype=float)
model = sm.OLS(height,X_l).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.799
Model:                            OLS   Adj. R-squared:                  0.751
Method:                 Least Squares   F-statistic:                     16.87
Date:                Mon, 05 Dec 2022   Prob (F-statistic):           9.38e-06
Time:                        02:43:37   Log-Likelihood:                -80.127
No. Observations:                  22   AIC:                             170.3
Df Residuals:                      17   BIC:                             175.7
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           122.4789     10.051     12.186      0.0

In [42]:
X_l = data3.iloc[:,[0,1,2,3]].values
X_l = np.array(X_l,dtype=float)
model = sm.OLS(height,X_l).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.795
Model:                            OLS   Adj. R-squared:                  0.761
Method:                 Least Squares   F-statistic:                     23.27
Date:                Mon, 05 Dec 2022   Prob (F-statistic):           2.03e-06
Time:                        02:43:58   Log-Likelihood:                -80.331
No. Observations:                  22   AIC:                             168.7
Df Residuals:                      18   BIC:                             173.0
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           125.8353      7.946     15.836      0.0